using Hris.SharedKernel;

namespace Hris.Modules.Timekeeping.Domain;

/// <summary>
/// Aggregate Root binding a <see cref="WorkShift"/> to an employee or organizational
/// unit for an effective period. Source:
/// docs/04-modules/timekeeping/domain/aggregates.md and shift-assignments.md.
///
/// This is deliberately its own root while <see cref="ScheduleAssignment"/> is not,
/// and aggregates.md states the asymmetry outright so it does not read as an
/// oversight. A <see cref="WorkShift"/> may be referenced by thousands of
/// assignments changing daily as rotations advance and swaps occur; loading the
/// whole shift to read or write one employee's assignment would make that aggregate
/// enormous and would serialise unrelated employees' changes against each other for
/// no domain reason. A swap additionally spans two assignments, potentially
/// referencing two different shifts, which is itself a reason it cannot live inside
/// either shift.
///
/// A superseded or expired assignment is retained, never deleted (TK-035). That is
/// what makes a dispute months later — "what shift was I assigned that day" —
/// answerable at all.
/// </summary>
public sealed class ShiftAssignment : AggregateRoot<ShiftAssignmentId>
{
    public Guid TenantId { get; }

    public AssignmentTargetType TargetType { get; }

    /// <summary>
    /// The employee or organizational unit this assignment binds. A plain string
    /// because the referenced module differs by <see cref="TargetLevel"/>, and every
    /// cross-module reference here is by identifier only.
    /// </summary>
    public string TargetId { get; }

    /// <summary>The precedence level, per aggregates.md's own ordering.</summary>
    public OrganizationalAssignmentLevel TargetLevel { get; }

    public WorkShiftId WorkShiftId { get; }

    public DateOnly EffectiveFrom { get; }

    public DateOnly? EffectiveTo { get; private set; }

    public ShiftAssignmentStatus Status { get; private set; }

    /// <summary>Present when generated by a rotation rather than assigned individually.</summary>
    public RotationCycleId? RotationCycleReference { get; }

    /// <summary>Present when this assignment resulted from a swap (TK-033).</summary>
    public ShiftAssignmentId? SwapLinkedAssignmentId { get; private set; }

    /// <summary>
    /// A proposed but not yet activated swap. Held on the primary assignment only;
    /// the counterpart is reached through
    /// <see cref="PendingShiftSwap.CounterpartAssignmentId"/>. Null once the swap
    /// activates or is abandoned.
    /// </summary>
    public PendingShiftSwap? PendingSwap { get; internal set; }

    /// <summary>Absent for system-generated rotation assignments, per TK-051.</summary>
    public Guid? AssignedBy { get; }

    public DateTimeOffset AssignedOn { get; }

    private ShiftAssignment(
        ShiftAssignmentId id, Guid tenantId, AssignmentTargetType targetType, string targetId,
        OrganizationalAssignmentLevel targetLevel, WorkShiftId workShiftId, DateOnly effectiveFrom,
        DateOnly? effectiveTo, RotationCycleId? rotationCycleReference, Guid? assignedBy, DateTimeOffset assignedOn)
        : base(id)
    {
        TenantId = tenantId;
        TargetType = targetType;
        TargetId = targetId;
        TargetLevel = targetLevel;
        WorkShiftId = workShiftId;
        EffectiveFrom = effectiveFrom;
        EffectiveTo = effectiveTo;
        Status = ShiftAssignmentStatus.Scheduled;
        RotationCycleReference = rotationCycleReference;
        AssignedBy = assignedBy;
        AssignedOn = assignedOn;
    }

    /// <summary>
    /// <paramref name="isTemporary"/> drives TK-032: a temporary assignment requires
    /// an end date and expires without administrative action, because one that must
    /// be manually ended will eventually be forgotten and quietly become permanent —
    /// the same reasoning Administration applies to delegation expiry.
    ///
    /// <paramref name="overlapsExistingIndividualAssignment"/> is TK-031, computed by
    /// the caller across this employee's other assignments, which no single aggregate
    /// instance can see.
    /// </summary>
    public static Result<ShiftAssignment> Create(
        ShiftAssignmentId id, Guid tenantId, AssignmentTargetType targetType, string? targetId,
        OrganizationalAssignmentLevel targetLevel, WorkShiftId workShiftId, DateOnly effectiveFrom,
        DateOnly? effectiveTo, bool isTemporary, RotationCycleId? rotationCycleReference,
        bool overlapsExistingIndividualAssignment, Guid? assignedBy, DateTimeOffset assignedOn)
    {
        if (string.IsNullOrWhiteSpace(targetId))
        {
            return Result.Failure<ShiftAssignment>(TimekeepingErrors.AssignmentTargetRequired);
        }

        var individualLevel = targetLevel == OrganizationalAssignmentLevel.IndividualEmployee;
        if (individualLevel != (targetType == AssignmentTargetType.Employee))
        {
            return Result.Failure<ShiftAssignment>(TimekeepingErrors.IndividualAssignmentRequiresEmployeeTarget);
        }

        if (isTemporary && effectiveTo is null)
        {
            return Result.Failure<ShiftAssignment>(TimekeepingErrors.TemporaryAssignmentRequiresEndDate);
        }

        if (effectiveTo is not null && effectiveTo.Value < effectiveFrom)
        {
            return Result.Failure<ShiftAssignment>(SharedKernelErrors.DateRangeEndBeforeStart);
        }

        if (individualLevel && overlapsExistingIndividualAssignment)
        {
            return Result.Failure<ShiftAssignment>(TimekeepingErrors.OverlappingIndividualAssignment);
        }

        var assignment = new ShiftAssignment(
            id, tenantId, targetType, targetId.Trim(), targetLevel, workShiftId, effectiveFrom, effectiveTo,
            rotationCycleReference, assignedBy, assignedOn);

        assignment.AddDomainEvent(new ShiftAssignmentCreated(
            Guid.NewGuid(), assignedOn, id, tenantId, targetType, targetId.Trim(), targetLevel, workShiftId,
            effectiveFrom, effectiveTo, rotationCycleReference, assignedBy));

        return Result.Success(assignment);
    }

    public Result Activate()
    {
        if (Status != ShiftAssignmentStatus.Scheduled)
        {
            return Result.Failure(TimekeepingErrors.AssignmentNotActiveOrScheduled);
        }

        Status = ShiftAssignmentStatus.Active;
        return Result.Success();
    }

    /// <summary>
    /// Step one of four. Records a proposal without changing what either employee is
    /// currently expected to work — a swap only one party has agreed to is not yet a
    /// swap, which is why proposing is separate from activating.
    /// </summary>
    public Result ProposeSwap(
        ShiftAssignmentId counterpartId, string? primaryEmployeeId, string? counterpartEmployeeId,
        DateOnly proposedEffectiveFrom, Guid initiatedBy)
    {
        if (counterpartId == Id)
        {
            return Result.Failure(TimekeepingErrors.SwapRequiresTwoDistinctAssignments);
        }

        if (Status is not (ShiftAssignmentStatus.Scheduled or ShiftAssignmentStatus.Active))
        {
            return Result.Failure(TimekeepingErrors.AssignmentNotActiveOrScheduled);
        }

        var swapResult = PendingShiftSwap.Create(
            counterpartId, proposedEffectiveFrom, initiatedBy, primaryEmployeeId, counterpartEmployeeId);
        if (swapResult.IsFailure)
        {
            return Result.Failure(swapResult.Error);
        }

        PendingSwap = swapResult.Value;
        return Result.Success();
    }

    /// <summary>
    /// Step two. Consent is matched to the named employee rather than counted, so
    /// one party agreeing twice can never satisfy TK-034.
    /// </summary>
    public Result ConsentToSwap(string? consentingEmployeeId)
    {
        if (PendingSwap is null)
        {
            return Result.Failure(TimekeepingErrors.SwapRequiresBothPartiesConsent);
        }

        if (string.Equals(consentingEmployeeId, PendingSwap.PrimaryEmployeeId, StringComparison.Ordinal))
        {
            PendingSwap.PrimaryConsented = true;
            return Result.Success();
        }

        if (string.Equals(consentingEmployeeId, PendingSwap.CounterpartEmployeeId, StringComparison.Ordinal))
        {
            PendingSwap.CounterpartConsented = true;
            return Result.Success();
        }

        return Result.Failure(TimekeepingErrors.SwapRequiresBothPartiesConsent);
    }

    /// <summary>
    /// Step three, optional. Substitutes for one or both consents where the acting
    /// user holds override authority — an operational necessity such as a supervisor
    /// resolving a no-show. Recorded distinctly, because an auditor's question is not
    /// whether the swap happened but on whose agreement.
    /// </summary>
    public Result OverrideSwapConsent(Guid overridingActor, string? reason, bool actorHoldsOverrideAuthority)
    {
        if (PendingSwap is null)
        {
            return Result.Failure(TimekeepingErrors.SwapRequiresBothPartiesConsent);
        }

        if (!actorHoldsOverrideAuthority)
        {
            return Result.Failure(TimekeepingErrors.SwapRequiresBothPartiesConsent);
        }

        PendingSwap.OverriddenBy = overridingActor;
        PendingSwap.OverrideReason = reason?.Trim();
        return Result.Success();
    }

    /// <summary>
    /// Step four. Marks this side swapped and links it to its counterpart. TK-033
    /// requires both sides to move: an implementation updating one employee's
    /// assignment and leaving the other's alone has not swapped anything, it has
    /// reassigned one person and left the second still expecting their original
    /// shift. The Application layer coordinates the pair; this method is one half.
    ///
    /// The event is raised by the coordinating use case rather than here, because
    /// domain-events.md requires exactly one <see cref="ShiftAssignmentSwapped"/> per
    /// swap carrying both sides, and neither half can see the other.
    /// </summary>
    public Result ActivateSwap(ShiftAssignmentId counterpartId)
    {
        if (counterpartId == Id)
        {
            return Result.Failure(TimekeepingErrors.SwapRequiresTwoDistinctAssignments);
        }

        if (Status is not (ShiftAssignmentStatus.Scheduled or ShiftAssignmentStatus.Active))
        {
            return Result.Failure(TimekeepingErrors.AssignmentNotActiveOrScheduled);
        }

        if (PendingSwap is not null && !PendingSwap.IsReadyToActivate)
        {
            return Result.Failure(TimekeepingErrors.SwapRequiresBothPartiesConsent);
        }

        Status = ShiftAssignmentStatus.Swapped;
        SwapLinkedAssignmentId = counterpartId;
        return Result.Success();
    }

    /// <summary>
    /// Raises the single <see cref="ShiftAssignmentSwapped"/> event for a completed
    /// swap and clears the proposal. Called on the primary side only, by the
    /// coordinating use case, because domain-events.md requires exactly one event per
    /// swap carrying both sides and neither aggregate can see the other.
    /// </summary>
    internal void RecordSwapCompleted(ShiftAssignment counterpart, PendingShiftSwap pending, DateTimeOffset nowUtc)
    {
        ArgumentNullException.ThrowIfNull(counterpart);
        ArgumentNullException.ThrowIfNull(pending);

        AddDomainEvent(new ShiftAssignmentSwapped(
            Guid.NewGuid(), nowUtc, TenantId, Id, TargetId, counterpart.Id, counterpart.TargetId,
            pending.ProposedEffectiveFrom, pending.PrimaryConsented && pending.CounterpartConsented,
            pending.OverriddenBy, pending.InitiatedBy));

        PendingSwap = null;
    }

    /// <summary>Automatic at end date, carrying no actor (TK-032, TK-051).</summary>
    public Result Expire(DateTimeOffset nowUtc)
    {
        if (Status == ShiftAssignmentStatus.Expired)
        {
            return Result.Success();
        }

        if (Status is not (ShiftAssignmentStatus.Scheduled or ShiftAssignmentStatus.Active))
        {
            return Result.Failure(TimekeepingErrors.AssignmentNotActiveOrScheduled);
        }

        if (EffectiveTo is null)
        {
            return Result.Failure(TimekeepingErrors.TemporaryAssignmentRequiresEndDate);
        }

        Status = ShiftAssignmentStatus.Expired;
        AddDomainEvent(new ShiftAssignmentExpired(Guid.NewGuid(), nowUtc, Id, TenantId, EffectiveTo.Value));
        return Result.Success();
    }

    public Result Cancel(string? reason, Guid cancelledBy, DateOnly effectiveDate, DateTimeOffset nowUtc)
    {
        if (Status == ShiftAssignmentStatus.Cancelled)
        {
            return Result.Success();
        }

        if (Status is not (ShiftAssignmentStatus.Scheduled or ShiftAssignmentStatus.Active))
        {
            return Result.Failure(TimekeepingErrors.AssignmentNotActiveOrScheduled);
        }

        Status = ShiftAssignmentStatus.Cancelled;
        EffectiveTo = effectiveDate;

        AddDomainEvent(new ShiftAssignmentCancelled(
            Guid.NewGuid(), nowUtc, Id, TenantId, reason?.Trim() ?? string.Empty, cancelledBy, effectiveDate));

        return Result.Success();
    }

    /// <summary>
    /// Whether this assignment governs <paramref name="date"/>. Cancelled and swapped
    /// assignments are excluded: both are retained as evidence (TK-035) but neither
    /// expresses what is currently expected.
    /// </summary>
    public bool AppliesOn(DateOnly date) =>
        Status is not (ShiftAssignmentStatus.Cancelled or ShiftAssignmentStatus.Swapped)
        && EffectiveFrom <= date
        && (EffectiveTo is null || date <= EffectiveTo.Value);

    public bool OverlapsPeriod(DateOnly from, DateOnly? to) =>
        (to is null || EffectiveFrom <= to.Value) && (EffectiveTo is null || from <= EffectiveTo.Value);
}
