using Hris.Modules.Employee.Domain;

namespace Hris.Modules.Employee.Application;

/// <summary>
/// The one place every command handler that needs to append an
/// <see cref="EmployeeHistory"/> record does so, per employee-history.md's own
/// "History records are generated by approved business processes" -- written
/// directly by the Application-layer command handler immediately after the
/// corresponding <see cref="Domain.Employee"/> operation succeeds, not through a
/// Domain Event subscriber; see <see cref="EmployeeHistory"/>'s own remarks on why.
/// </summary>
internal static class EmployeeHistoryRecorder
{
    public static Task RecordAsync(
        IEmployeeHistoryRepository repository, Guid tenantId, Guid employeeId, EmployeeHistoryCategory category,
        string? previousValue, string? newValue, DateTimeOffset nowUtc, CancellationToken cancellationToken)
    {
        var history = EmployeeHistory.Record(
            new EmployeeHistoryId(Guid.NewGuid()), tenantId, employeeId, category, previousValue, newValue,
            DateOnly.FromDateTime(nowUtc.UtcDateTime), null, null, nowUtc);

        return repository.AddAsync(history, cancellationToken);
    }
}
